// Builds the terminal into one file to paste into Cloudflare (dist/worker.js),
// plus src/assets.js for the tests. Run with: cd terminal && npm run build
//
//   src/lib.js     the market maths, shared by the Worker and the page
//   src/app.html   the page; /*LIB*/ marks where lib.js goes
//   src/fonts/     brand fonts (Latin subsets of signals/fonts), served by the Worker
//   src/worker.js  the Worker
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const read = (f) => fs.readFileSync(path.join(dir, f), 'utf8');

// ES module syntax -> plain script: the page and the bundle share one scope.
const lib = read('src/lib.js').replace(/^export (const|function|async function) /gm, '$1 ');
const html = read('src/app.html');
if (!html.includes('/*LIB*/')) throw new Error('app.html has no /*LIB*/ marker');
const page = html.replace('/*LIB*/', () => lib);

const fonts = Object.fromEntries(
  fs.readdirSync(path.join(dir, 'src/fonts')).filter((f) => f.endsWith('.woff2')).sort()
    .map((f) => [f, fs.readFileSync(path.join(dir, 'src/fonts', f)).toString('base64')]),
);

const assets = `// Generated by build.mjs from app.html, lib.js and fonts/. Don't edit.\n` +
  `export const PAGE = ${JSON.stringify(page)};\nexport const FONTS = ${JSON.stringify(fonts)};\n`;
fs.writeFileSync(path.join(dir, 'src/assets.js'), assets);

const worker = read('src/worker.js')
  .replace(/^import .*\n/gm, '')
  .replace(/^export (async function|function) /gm, '$1 ');
const bundle = [
  '// TCP Quant Terminal: one file for the Cloudflare dashboard (Edit code, paste, Deploy).',
  '// Built by terminal/build.mjs from terminal/src; edit those files, not this one.',
  '',
  lib.replace(/^\/\/ TCP Quant Terminal: the market maths.*\n/, ''),
  `const PAGE = ${JSON.stringify(page)};`,
  `const FONTS = ${JSON.stringify(fonts)};`,
  '',
  worker,
].join('\n');
fs.mkdirSync(path.join(dir, 'dist'), { recursive: true });
fs.writeFileSync(path.join(dir, 'dist/worker.js'), bundle);
console.log(`dist/worker.js ${(bundle.length / 1024).toFixed(0)} KB (page ${(page.length / 1024).toFixed(0)} KB, ${Object.keys(fonts).length} fonts)`);
