// Builds the terminal into one file to paste into Cloudflare (dist/worker.js),
// plus src/assets.js for the tests. Run with: cd terminal && npm install && npm run build
//
//   src/lib.js            the market maths, shared by the Worker and the page
//   src/playbook-lib.js   the Playbook's maths, shared by the Worker and the page
//   src/brief-lib.js      the session briefs' maths, shared by the Worker and the page
//   src/ranks-lib.js      the leaderboard's maths, shared by the Worker and the page
//   src/app.html          the page's markup; /*CSS*/ and /*SCRIPT*/ mark where the rest goes
//   src/app.css           the page's styles
//   src/playbook-page.js  the page's Playbook (the shared maths go in front of it)
//   src/brief-page.js     the page's session briefs
//   src/rank-page.js      the page's leaderboard and MT5 connection
//   src/app.js            the rest of the page's script
//   src/fonts/            brand fonts (Latin subsets of signals/fonts), served by the Worker
//   src/playbook.js       the Worker's Playbook: storage, posts and the 5-minute check
//   src/briefs.js         the Worker's session briefs: TCP AI's reads, posts, reminders and reviews
//   src/mt5.js            the Worker's MT5 links and leaderboard, and the TCP bridge's endpoints
//   src/worker.js         the Worker
// The Anthropic SDK (for TCP AI) is bundled from node_modules with esbuild, its licence kept.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const dir = path.dirname(fileURLToPath(import.meta.url));
const read = (f) => fs.readFileSync(path.join(dir, f), 'utf8');

// ES module syntax -> plain script: each of the page and the bundle is one scope.
const plain = (file) => read(file)
  .replace(/^import [\s\S]*? from '[^']+';\n/gm, '')
  .replace(/^export (const|function|async function) /gm, '$1 ');
const lib = plain('src/lib.js');
const shared = [lib, plain('src/playbook-lib.js'), plain('src/brief-lib.js'), plain('src/ranks-lib.js')].join('\n');
const html = read('src/app.html');
for (const marker of ['/*CSS*/', '/*SCRIPT*/']) if (!html.includes(marker)) throw new Error(`app.html has no ${marker} marker`);
const page = html.replace('/*CSS*/', () => read('src/app.css'))
  .replace('/*SCRIPT*/', () => [shared, read('src/playbook-page.js'), read('src/brief-page.js'), read('src/rank-page.js'), read('src/app.js')].join('\n'));

const fonts = Object.fromEntries(
  fs.readdirSync(path.join(dir, 'src/fonts')).filter((f) => f.endsWith('.woff2')).sort()
    .map((f) => [f, fs.readFileSync(path.join(dir, 'src/fonts', f)).toString('base64')]),
);

const assets = `// Generated by build.mjs from app.html, lib.js and fonts/. Don't edit.\n` +
  `export const PAGE = ${JSON.stringify(page)};\nexport const FONTS = ${JSON.stringify(fonts)};\n`;
fs.writeFileSync(path.join(dir, 'src/assets.js'), assets);

// The SDK for Workers: the browser build (Node's file and process modules swapped for stubs),
// one scope of its own, exposing Anthropic and toFile to briefs.js.
const sdk = await esbuild.build({
  stdin: { contents: "export { default as Anthropic, toFile } from '@anthropic-ai/sdk';", resolveDir: dir, loader: 'js' },
  bundle: true, format: 'iife', globalName: '__anthropic', platform: 'browser', external: ['node:*'],
  target: 'es2022', minify: true, write: false, metafile: true, legalComments: 'none', logLevel: 'warning',
});
const sdkCode = sdk.outputFiles[0].text.trim();
// Workers have no Node modules: none may be loaded (a mention inside an error message is fine).
if (/\bimport\("node:/.test(sdkCode)) throw new Error('the SDK bundle still loads a Node module');
const licences = [...new Set(Object.keys(sdk.metafile.inputs).map((p) => (p.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/) || [])[1]).filter(Boolean))]
  .sort().map((name) => {
    const root = path.join(dir, 'node_modules', name);
    const { version, license } = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
    const file = fs.readdirSync(root).find((f) => /^licen[cs]e/i.test(f));
    const text = file ? fs.readFileSync(path.join(root, file), 'utf8').trim().replace(/\*\//g, '* /') : `${license} licence`;
    return `/*! ${name} ${version}\n${text}\n*/`;
  });

const bundle = [
  '// TCP Quant Terminal: one file for the Cloudflare dashboard (Edit code, paste, Deploy).',
  '// Built by terminal/build.mjs from terminal/src; edit those files, not this one.',
  '',
  shared.replace(/^\/\/ TCP Quant Terminal: the market maths.*\n/, ''),
  `const PAGE = ${JSON.stringify(page)};`,
  `const FONTS = ${JSON.stringify(fonts)};`,
  '',
  '// The Anthropic SDK and what it bundles, with their licences.',
  ...licences,
  sdkCode,
  'const { Anthropic, toFile } = __anthropic;',
  '',
  plain('src/playbook.js'),
  plain('src/briefs.js'),
  plain('src/mt5.js'),
  plain('src/worker.js'),
].join('\n');
fs.mkdirSync(path.join(dir, 'dist'), { recursive: true });
fs.writeFileSync(path.join(dir, 'dist/worker.js'), bundle);
console.log(`dist/worker.js ${(bundle.length / 1024).toFixed(0)} KB (page ${(page.length / 1024).toFixed(0)} KB, ${Object.keys(fonts).length} fonts, SDK ${(sdkCode.length / 1024).toFixed(0)} KB)`);
