// Builds the terminal into one file to paste into Cloudflare (dist/worker.js),
// plus src/assets.js for the tests. Run with: cd terminal && npm run build
//
//   src/lib.js            the market maths, shared by the Worker and the page
//   src/playbook-lib.js   the Playbook's maths, shared by the Worker and the page
//   src/app.html          the page's markup; /*CSS*/ and /*SCRIPT*/ mark where the rest goes
//   src/app.css           the page's styles
//   src/playbook-page.js  the page's Playbook (the shared maths go in front of it)
//   src/app.js            the rest of the page's script
//   src/fonts/            brand fonts (Latin subsets of signals/fonts), served by the Worker
//   src/playbook.js       the Worker's Playbook: storage, posts and the 5-minute check
//   src/worker.js         the Worker
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const read = (f) => fs.readFileSync(path.join(dir, f), 'utf8');

// ES module syntax -> plain script: each of the page and the bundle is one scope.
const plain = (file) => read(file)
  .replace(/^import [\s\S]*? from '[^']+';\n/gm, '')
  .replace(/^export (const|function|async function) /gm, '$1 ');
const lib = plain('src/lib.js');
const shared = `${lib}\n${plain('src/playbook-lib.js')}`;
const html = read('src/app.html');
for (const marker of ['/*CSS*/', '/*SCRIPT*/']) if (!html.includes(marker)) throw new Error(`app.html has no ${marker} marker`);
const page = html.replace('/*CSS*/', () => read('src/app.css'))
  .replace('/*SCRIPT*/', () => [shared, read('src/playbook-page.js'), read('src/app.js')].join('\n'));

const fonts = Object.fromEntries(
  fs.readdirSync(path.join(dir, 'src/fonts')).filter((f) => f.endsWith('.woff2')).sort()
    .map((f) => [f, fs.readFileSync(path.join(dir, 'src/fonts', f)).toString('base64')]),
);

const assets = `// Generated by build.mjs from app.html, lib.js and fonts/. Don't edit.\n` +
  `export const PAGE = ${JSON.stringify(page)};\nexport const FONTS = ${JSON.stringify(fonts)};\n`;
fs.writeFileSync(path.join(dir, 'src/assets.js'), assets);

const bundle = [
  '// TCP Quant Terminal: one file for the Cloudflare dashboard (Edit code, paste, Deploy).',
  '// Built by terminal/build.mjs from terminal/src; edit those files, not this one.',
  '',
  shared.replace(/^\/\/ TCP Quant Terminal: the market maths.*\n/, ''),
  `const PAGE = ${JSON.stringify(page)};`,
  `const FONTS = ${JSON.stringify(fonts)};`,
  '',
  plain('src/playbook.js'),
  plain('src/worker.js'),
].join('\n');
fs.mkdirSync(path.join(dir, 'dist'), { recursive: true });
fs.writeFileSync(path.join(dir, 'dist/worker.js'), bundle);
console.log(`dist/worker.js ${(bundle.length / 1024).toFixed(0)} KB (page ${(page.length / 1024).toFixed(0)} KB, ${Object.keys(fonts).length} fonts)`);
